[tool.poetry]
name = "hnreader"
version = "0.1.0"
description = ""
authors = ["Lukas Winkler <git@lw1.at>"]

[tool.poetry.dependencies]
python = "^3.9"
aredis = {extras = ["hiredis"], version = "^1.1.8"}
hiredis = "^2.0.0"
starlette = "^0.18.0"
uvicorn = "^0.17.0"
gunicorn = "^20.1.0"
uvloop = "^0.16.0"
httptools = "^0.4.0"
setproctitle = "^1.2.2"
httpx = "^0.22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
