[tool.poetry]
name = "hnreader"
version = "0.1.0"
description = ""
authors = ["Lukas Winkler <git@lw1.at>"]

[tool.poetry.dependencies]
python = "^3.9"
aredis = {extras = ["hiredis"], version = "^1.1.8"}
hiredis = "^2.0.0"
aiohttp = "^3.7.4"
starlette = "^0.14.2"
uvicorn = "^0.13.4"
gunicorn = "^20.1.0"
uvloop = "^0.15.2"
httptools = "^0.1.1"
setproctitle = "^1.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
